### ISSUE TITLE
安装文档操作，却无法正常运行

### ISSUE THREAD

**Issue by sillyY** [BuptStEve/vuepress-plugin-demo-code#10]
按照文档上的步骤，代码全是复制示例代码
- 1. 安装了指定的版本 `vuepres v1.x `
![image](https://user-images.githubusercontent.com/20504116/61958785-964cb000-aff4-11e9-99fc-c3b06d42ee1b.png)
- 2. 设置plugin
![image](https://user-images.githubusercontent.com/20504116/61958926-e0359600-aff4-11e9-92c0-b22cfcd02e11.png)
- 3. Markdown引入
![image](https://user-images.githubusercontent.com/20504116/61958981-fb080a80-aff4-11e9-8646-bd1c9393aebd.png)
- 4. 页面展示
![image](https://user-images.githubusercontent.com/20504116/61959065-2985e580-aff5-11e9-86b0-711134bfb114.png)
![image](https://user-images.githubusercontent.com/20504116/61959085-330f4d80-aff5-11e9-9511-e54621f00ec9.png)

按照以上操作，应该是无问题的，但结果却跟我想的不一样。既不呈现已有的效果，也不报错。
之前也尝试了`vuepress-plugin-demo-block `这个库，但也是同样的结果，我尝试了替换vuepress版本与他的版本一致，解决了这个问题。 它的版本是"`^1.0.0-alpha.30`"，但由于某些其他需求不支持，故放弃了该库。
然后也尝试替换该库的`vuepress`版本至`^1.0.0-alpha.39`， 但安装完，运行时抛出了异常.
```
cannot find module '@vuepress/core/lib/prepare'
```

在尝试了许久后，我实在找不到解决方案，故在此求教，谢谢了

**Comment by BuptStEve** [comment]
有复现仓库么？

**Comment by BuptStEve** [comment]
你把 mark 设置成了这个，所以需要用

```
::: demo-code
your code
:::
```

![image](https://user-images.githubusercontent.com/11501493/61959690-87ff9380-aff6-11e9-95ca-495b104ee0c5.png)

**Comment by BuptStEve** [comment]
https://buptsteve.github.io/vuepress-plugin-demo-code/zh/#democodemark

**Comment by BuptStEve** [comment]
一般来说啥都不配就行，就设置 

```js
plugins: ['demo-code'],
```

就能跑，觉得哪儿不爽了可以再改配置。

**Comment by sillyY** [comment]
@BuptStEve 刚有事去了，我修改了demoCodeMark,甚至于修改成plugins: ['demo-code'],结果还是不行。仓库地址[ele-vue](https://github.com/sillyY/ele-vue.git) master分支， docs里
