### ISSUE TITLE
feat: "Show more" and "hide" can be optional

### ISSUE THREAD

**Issue by leandrofngl** [BuptStEve/vuepress-plugin-demo-code#13]
There could be an option not to display the "Show more" and "Hide" buttons, like:

```
['demo-code', {
    collapsible: false
}]
```

**Comment by BuptStEve** [comment]
LGTM, would you like to work on this yourself?

**Comment by BuptStEve** [comment]
BTW, for now you can set [`minHeight`](https://github.com/BuptStEve/vuepress-plugin-demo-code#minheight) to a large number to always hide the buttons.
