### ISSUE TITLE
feat: Performance Issue

### ISSUE THREAD

**Issue by tianjianchn** [BuptStEve/vuepress-plugin-demo-code#16]
**Is your feature request related to a problem? Please describe.**
With a long demo code, after highlighted and insert into markdown render, Vue takes such a long time to render(+10s).

**Describe the solution you'd like**
https://github.com/BuptStEve/vuepress-plugin-demo-code/blob/ee0b88322a4e498d173bb3f894dfd3e4d692b831/src/index.js#L93-L95

instead of inserting the highlighted html into the markdown, use v-html to render it at runtime in DemoAndCode.vue

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by BuptStEve** [comment]
Bravo!  
It's about `15947 ms VS 1212 ms`

**Comment by BuptStEve** [comment]
@all-contributors add @tianjianchn for bug
