### ISSUE TITLE
不支持 element-ui 

### ISSUE THREAD

**Issue by luoxionghui** [BuptStEve/vuepress-plugin-demo-code#24]
安装了插件、element-ui 。但是不能正常显示element-ui 的显示

**Comment by BuptStEve** [comment]
提供一下复现仓库

**Comment by BuptStEve** [comment]
https://v1.vuepress.vuejs.org/zh/guide/basic-config.html#%E5%BA%94%E7%94%A8%E7%BA%A7%E5%88%AB%E7%9A%84%E9%85%8D%E7%BD%AE

**Comment by BuptStEve** [comment]
解决了么？先关了哈，有问题你再开~
