### ISSUE TITLE
BUG: Multiple export scripts replace each other

### ISSUE THREAD

**Issue by henrikdahl** [BuptStEve/vuepress-plugin-demo-code#25]
**Version**
Latest

**Describe the bug**
If you have multiple two way binding data in multiple scripts, only the last one remains (they replace each other). Here is more information: https://github.com/vuepress/vuepress-community/issues/20#issuecomment-595316285

**Comment by BuptStEve** [comment]
For now, we can only write one `export default`.
Maybe combine the demos into one?

```html
<template>
  ## foo
  <input :disabled="disabled1" />

  ## bar
  <input :disabled="disabled2" />
</template>

<script>
export default {
  data() {
    return {
      disabled1: true,
      disabled2: true,
    }
  }
}
</script>
```

Or how about trying https://github.com/xiguaxigua/vuepress-plugin-demo-block?

**Comment by henrikdahl** [comment]
Thanks for the reply.

Been trying to solve it myself but seems every solution has a different downside. Hard to get it to work properly in every senario.

**Comment by calebman** [comment]
Try this plugin https://github.com/calebman/vuepress-plugin-demo-container?

Good support for multiple examples.
