### ISSUE TITLE
希望添加折叠 功能

### ISSUE THREAD

**Issue by xu455255849** [BuptStEve/vuepress-plugin-demo-code#31]
希望能够折叠代码，点击 显示代码后显示  再次点击 折叠，
感觉这个功能非常重要

**Comment by BuptStEve** [comment]
啥意思，不是可以折叠么？
你指的是不显示？minHeight 设为0试试？

**Comment by xu455255849** [comment]
我重写了样式解决了， 不过现在好像有一个问题，就是第一次进页面 组件不展示，需要点击切一下路由 才正常展示。。也没报错。。不知道啥情况

**Comment by BuptStEve** [comment]
> 我重写了样式解决了， 不过现在好像有一个问题，就是第一次进页面 组件不展示，需要点击切一下路由 才正常展示。。也没报错。。不知道啥情况

给个复现仓库看看？

**Comment by xu455255849** [comment]
内部仓库，不太好弄，等开源我再看看，这个issues 先关了
