### ISSUE TITLE
构建后 首次打开直接渲染成 custom-element

### ISSUE THREAD

**Issue by xu455255849** [BuptStEve/vuepress-plugin-demo-code#32]
https://github.com/BuptStEve/vuepress-plugin-demo-code/issues/26

借这个issue 问一个问题，我也是自建的组件库，现在有一个问题就是 build 后打开线上服务 第一次 组件不会正常 渲染。
比如 <rc-button>1<rc-button> 会直接直接渲染出来 而不会 正常渲染成这个组件，比如这样的
<button>
  <span></span>
</button

点击一下页面的导航切换一下URL 后面就都展示正常了，

**Comment by xu455255849** [comment]
好像代码被过滤了

```
<rc-button></rc-button>
```

**Comment by BuptStEve** [comment]
给个复现仓库？
