### ISSUE TITLE
bug: minHeight not working

### ISSUE THREAD

**Issue by kinow** [BuptStEve/vuepress-plugin-demo-code#35]
**Version**
Version 0.5.2

**Describe the bug**

Tried array and object configuration, in both the `minHeight` set to `0` or `1` is ignored. It keeps using the default value of `200` no matter the value I pass.

**To Reproduce**

I used the following configuration:

```js
module.exports = {
  plugins: {
    'demo-code': {
      showText: 'show code',
      hideText: 'hide',
      minHeight: 0,
      onlineBtns: {
        codepen: false,
        jsfiddle: false,
        codesandbox: false,
      }
    }
  }
}
```

**Expected behavior**

`minHeight` set to `0` (or any value provided by the user)

**Additional context**

Thanks!

**Comment by BuptStEve** [comment]
![image](https://user-images.githubusercontent.com/11501493/120880490-8002d880-c5fd-11eb-962f-87b7ed927b33.png)

Can't reproduce, maybe you should save your `*.md` file to trigger render.

**Comment by kinow** [comment]
I first noticed it at $work laptop. And reported the issue from home laptop after seeing it again. Will try a codepen later to see if I can create a minimal example to reproduce it.
