### ISSUE TITLE
bug: 滚动位置错误

### ISSUE THREAD

**Issue by pz25925** [BuptStEve/vuepress-plugin-demo-code#39]
**版本**
Version 0.6.0

**描述一下 bug**
展开 code，收缩 code，滚动条位置不对

是否考虑删除

```
// DemoAndCode.vue
window.scrollTo({ top: this.scrollTop, behavior: 'smooth' })
```

**Comment by BuptStEve** [comment]
来个图？

**Comment by pz25925** [comment]
> 来个图？

官方 demo 可以复现。

展开代码：
![image](https://user-images.githubusercontent.com/12759499/130087416-0710d87e-fbf8-488c-ac1f-65f19808fb6e.png)
收缩代码：
![image](https://user-images.githubusercontent.com/12759499/130087558-f6e0b350-4efc-4e14-b974-790b399f05a3.png)

**Comment by BuptStEve** [comment]
> > 来个图？
> 
> 官方 demo 可以复现，应该是个 feature，但是交互上稍微感觉有点奇怪。
> 
> 展开代码：
> ![image](https://user-images.githubusercontent.com/12759499/130087416-0710d87e-fbf8-488c-ac1f-65f19808fb6e.png)
> 收缩代码：
> ![image](https://user-images.githubusercontent.com/12759499/130087558-f6e0b350-4efc-4e14-b974-790b399f05a3.png)

哦这个确实是个 feature...
还有优化空间就是了...
