### ISSUE TITLE
安装完无法运行，还是原文解析文本

### ISSUE THREAD

**Issue by songbambi** [BuptStEve/vuepress-plugin-demo-code#5]
**版本**
Version [e.g. 0.1.0]

安装了最新的1。x   vuepress
然后。vuepress 的config 插件配置里，根据文档写了使用了插件
md中写 :::demo xxx ::: 格式无法生效，md文档内实时展示还是写的文本标签，插件没生效

感谢！

**描述一下 bug**
简洁清晰地描述一下 bug。如果方便的话，添加一些截图描述你的问题。

**复现 bug**
复现的步骤：

1. 首先 '...'
2. 点击了 '...'
3. 滚动到了 '...'
4. 看到了错误

如果方便的话：

* 复现 bug 的在线地址：
  * codepen: https://codepen.io/
  * jsfiddle: https://jsfiddle.net/
  * codesandbox: https://codesandbox.io/
* 复现 bug 的仓库地址：https://github.com/new

**预期行为**
简洁清晰地描述一下预期行为。

**附加上下文**
添加一些问题的相关上下文。

**Comment by BuptStEve** [comment]
能提供一下复现 bug 的仓库么？

```
:::demo xxx :::
```

`:::` 后面写空格了么？

**Comment by songbambi** [comment]
感谢，这里是仓库。 vuepress 在启动的时候就提示加载插件失败

[仓库地址](https://github.com/songbambi/vuepresstest)

**Comment by BuptStEve** [comment]
> 感谢，这里是仓库。 vuepress 在启动的时候就提示加载插件失败
> 
> [仓库地址](https://github.com/songbambi/vuepresstest)

我试一下，估计是全局安装 vuepress 导致找不到插件的原因...

**Comment by songbambi** [comment]
搞定，十分感谢作者。

**Comment by BuptStEve** [comment]
> 搞定，十分感谢作者。

没事儿，原因是全局安装了 vuepress，但插件是本地安装的，导致在启动时 vuepress 找不到插件。翻了下源码，没法兼容这种情况。

所以唯一解决方案就是本地装个 vuepress。
