### ISSUE TITLE
feat: 对组件引入的支持，和对pug语法的支持

### ISSUE THREAD

**Issue by xkloveme** [BuptStEve/vuepress-plugin-demo-code#8]
**你的功能请求是否与某些问题相关？请描述**
简洁清晰地描述一下当前有什么问题。如果方便的话，添加一些截图描述你的问题。

**描述您想要的解决方案**
简洁清晰地描述一下你想要的特性是怎样的。

**描述你考虑过的备选方案**
简洁清晰地描述一下你考虑过的其他备选方案，可能会有什么问题。

**附加上下文**
添加一些问题的相关上下文。

**Comment by BuptStEve** [comment]
举个例子？

**Comment by BuptStEve** [comment]
先关了哈，有补充的话可以再打开~
