### ISSUE TITLE
bug: 每次挂载组件之后，都会有个收缩的过程

### ISSUE THREAD

**Issue by jardenliu** [BuptStEve/vuepress-plugin-demo-code#9]
**版本**
Version 0.3.5

**描述一下 bug**
DemoAndCode.vue里面 isShowCode 默认true mounted之后才变成了false. 这会先挂载展开的code再收缩起来。设计如此，还是有问题？

**复现 bug**
复现的步骤：心领神会

1. 心领神会
2. 进入页面
3. 用力一看

**Comment by BuptStEve** [comment]
设计如此：

* 基于 max-height 做动画
* 暗示这里可以展开

**Comment by jardenliu** [comment]
- 这..........还需要暗示吗？那么大的字写着显示代码.。
-  可以从隐藏的代码块获取高度，可以不用从code-wrapper获取高度吧。
- 感觉还是一进来就默认收起，会显得比较简洁。

纯属个人见解，不知合理与否，如有冒犯，请大神忽略~~

**Comment by BuptStEve** [comment]
> * 这..........还需要暗示吗？那么大的字写着显示代码.。
> * 可以从隐藏的代码块获取高度，可以不用从code-wrapper获取高度吧。
> * 感觉还是一进来就默认收起，会显得比较简洁。
> 
> 纯属个人见解，不知合理与否，如有冒犯，请大神忽略~~

大神不敢当，欢迎提 pr
